### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by OrangINDO12** [NCVV-Dev/FVV-Site#2]
when im going to the 2th matchmaking it stuck on the 'Pasrsing Game Info...' when im using fedoraware. If im not using fedoraware it will not stop on 'Pasrsing Game Info...' So What Do I do?
![Screenshot (45)](https://github.com/NCVV-Dev/FVV-Site/assets/157898415/2fb9d583-fd7e-4088-99a8-6a3b611e5f99)

**Comment by harmonyzt** [comment]
Hey there! Sorry but this isn't the right place for such an issue. Try using search engines for such problem you experience!
